// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvsU_udIjMwQCnjSvCJhPZB-3la92ePsU',
    appId: '1:1090153622568:web:eb4dbb87e3f83114be191d',
    messagingSenderId: '1090153622568',
    projectId: 'rate-me-db2d9',
    authDomain: 'rate-me-db2d9.firebaseapp.com',
    storageBucket: 'rate-me-db2d9.appspot.com',
    measurementId: 'G-Q7NHNSPVXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmmpiT1rrW-C3vR2DxZd4rMg5FGhCfkJQ',
    appId: '1:1090153622568:android:90baa09b495d13c3be191d',
    messagingSenderId: '1090153622568',
    projectId: 'rate-me-db2d9',
    storageBucket: 'rate-me-db2d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkeuVUHBGP8pGTJbqUD5kfuxPGf7B6q9s',
    appId: '1:1090153622568:ios:3ed565f24fb418f7be191d',
    messagingSenderId: '1090153622568',
    projectId: 'rate-me-db2d9',
    storageBucket: 'rate-me-db2d9.appspot.com',
    iosClientId: '1090153622568-ae18rh49tmrd3sp1jldd5u3bt6nkbpme.apps.googleusercontent.com',
    iosBundleId: 'com.example.rateMe',
  );
}
